### ISSUE TITLE
关于集成了One Step功能的Nexus6的刷机包

### ISSUE THREAD

**Issue by liboshi** [SmartisanTech/SmartisanOS_Build_Release#2]
关于集成了One Step功能的Nexus6的刷机包的问题：

- 此刷机包是Smartisan OS吗？如果是，请问可以收到系统更新吗？

**Comment by zhangjizxc** [comment]
不是,原生Android系统. 只修改了oneStep功能.  集成了大爆炸功能的包正在上传.
