### ISSUE TITLE
Nexus6的刷机包脚本拼写错误

### ISSUE THREAD

**Issue by ishell** [SmartisanTech/SmartisanOS_Build_Release#3]
从`http://dl2.smartisan.cn/shuaji/other_phone/opensource/nexus6_shamu_20170112_mob31k.7z`下载刷机包后，
`flash-all.sh`里面的23行`fastboot -w update image-shamu-mob31k.zip` 应该为`fastboot -w update images-shamu-mob31k.zip`。
但是我改完之后出现了如下错误：
 ```
  (bootloader) slot-count: not found
  (bootloader) slot-suffixes: not found
  (bootloader) slot-suffixes: not found
  archive does not contain 'android-info.txt'
  error: update package 'images-shamu-mob31k.zip' has no android-info.txt
 ```
貌似刷机包不完整。

**Comment by codingbyai** [comment]
抱歉，之前的压缩包里的zip文件有点问题，请下载新的刷机包。
