### ISSUE TITLE
Nexus 6 Big Bang issue

### ISSUE THREAD

**Issue by gongzelong0718** [SmartisanTech/SmartisanOS_Build_Release#5]
Nexus6刷完Build后，直接在浏览器打开baidu.com，长按新闻正文，并没有大爆炸啊，是什么原因呢？
有什么东西失效了吗？

**Comment by codingbyai** [comment]
https://github.com/SmartisanTech/android  这里的README有说明，webview不支持，需要改浏览器内核。

**Comment by gongzelong0718** [comment]
@huangxin813 thanks for your reply. Someone reminds me to reply in English.

So how to use or test the Big Bang feature? 
I never saw it can explode to many pieces of text. 
Is the server side broken down now?
Could you provide a gif or something to show the effect?

BTS, Why is webview not supported? Could you provide more details about that?
I may help to change the Chromium codes.

**Comment by codingbyai** [comment]
手指按压TextView上的文字会触发大爆炸。
分词用的三角兽提供的接口，我刚试了下，接口还能用。
webview那个，是因为需要修改浏览器内核，各个浏览器使用的内核不一定一样。
